import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import "./globals.css";

import { ApiContextProvider } from "./context/api.context";

import { Content, Container } from "./styles";

import Navbar from "./Components/Navbar";

import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marvel App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApiContextProvider>
      <html lang="en">
        <body className={roboto.className}>
          <Navbar />
          <Content>
            <Container>{children}</Container>
          </Content>
          <Footer />
        </body>
      </html>
    </ApiContextProvider>
  );
}
